"""Bone-name mapping tables for "Import clip", and their pure parser/matcher.

"Import clip" brings in an animation authored against someone else's skeleton
(a Mixamo FBX/GLB download, a Rigify metarig export) and converts it onto a
Warlock humanoid template rig. **This is never called "retarget" here** --
that word already means triangle-budget re-optimisation in this codebase
(``pipelines/optimize.py``), and reusing it for skeleton conversion would make
every future grep for one feature return hits for the other.

This module is only the bone-name side of that: which external bone names
correspond to which template bones, and matching a mapping table against a
skeleton the app has never seen before. The Blender sampling op that reads an
external animation's transforms and the rotation math that expresses them
against the template rig are later steps -- deliberately not here, so this
stays importable and testable with no Blender, exactly like ``rigging.py``'s
own template registry.

**A clip map's ``bones`` entry is an ordered chain, not a single name**,
because one external rig's bone sometimes has to collapse onto one template
bone: Rigify's ``DEF-spine.002``/``DEF-spine.003`` both become Warlock's
single ``chest``, and Mixamo's single ``Spine1``/``Spine2`` split the same way
depending on which Mixamo export era you have (folded into ``chest`` here
either way). The later math this sets up for -- not implemented in this
module -- reads the *last* bone's orientation and the direction from the
*first* bone's head to the *last* bone's tail; that convention is why chain
order matters and is preserved through parsing.

**Older Rigify metarigs number the neck differently.** A metarig generated by
an older Rigify version can end the spine chain one or two segments earlier
and start the neck deform bones at a different index than
``rigify.json`` assumes (``DEF-spine.004``/``DEF-spine.005``/``DEF-spine.006``
for neck+neck+head here). A metarig like that will leave ``neck`` and/or
``head`` at rest rather than mis-map them onto the wrong vertebra -- silently
wrong is worse than visibly unposed for a feature whose whole job is getting
someone else's animation to look right on a Warlock rig. Widening
``rigify.json`` to tolerate more than one numbering scheme is future work, not
a bug in this one.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

from . import rigging

log = logging.getLogger(__name__)

__all__ = [
    "CLIP_MAP_DIR",
    "ClipMap",
    "ClipMapError",
    "MatchResult",
    "parse_clip_map",
    "load_clip_maps",
    "normalise",
    "match",
]

#: Shipped clip maps, one file per external rig family. A sibling of
#: ``rigging.CLIP_DIR`` (the Troupe pose-clip library) rather than the same
#: directory: that one holds *poses*, keyed by template, and this holds
#: *bone-name tables*, keyed by external rig -- conflating the two would put
#: an external-rig JSON file in a glob that ``rigging._load_clip_library``
#: already walks and tries to parse as a pose library.
CLIP_MAP_DIR = rigging.TEMPLATE_DIR / "clip_maps"


class ClipMapError(ValueError):
    """A clip map, or a skeleton matched against one, that cannot be trusted.

    Always raised with one sentence naming the specific problem -- which field,
    which bone -- the same contract ``rigging.RigError``'s message follows,
    so a refusal at either the parse door or the match door is legible without
    a traceback.
    """


@dataclass(frozen=True, slots=True)
class ClipMap:
    """One external rig family's bone-name table, already validated.

    ``bones`` maps a *template* bone name to the ordered chain of *external*
    source bones that collapse onto it (first-to-last down the external rig's
    own hierarchy) -- see the module docstring for why a chain and not a
    single name. ``strip`` is compiled so ``normalise`` never recompiles a
    pattern per bone per skeleton.
    """

    key: str
    label: str
    template: str
    strip: re.Pattern[str]
    required: tuple[str, ...]
    root: str
    bones: Mapping[str, tuple[str, ...]]


def parse_clip_map(raw: Mapping[str, Any], *, source: str) -> ClipMap:
    """One clip map's contents, validated, or :class:`ClipMapError`.

    ``source`` names what this came from in every error message; when the map
    is loaded from a shipped file it is that file's stem, and the map's own
    ``key`` must equal it -- the rule ``rigging._load_templates`` applies to a
    skeleton template's key and filename, for the same reason: the Poser UI
    interpolates a clip map's key into a control's id, and a key naming a
    different file than the one that produced it would make an error message
    point at the wrong table.

    Checked, in order: the version is 1; ``template`` names a real skeleton
    template; every ``bones`` key is a bone of that template; every chain is a
    non-empty list of non-empty bone names; no external bone is claimed by two
    chains (an ambiguity a later sampling pass could not resolve either);
    ``required`` is a list of bone names that are all mapped; ``root`` is
    mapped; ``strip`` compiles as a regex; ``key``/``label`` are non-empty and
    ``key`` matches ``source``.
    """
    if raw.get("version") != 1:
        raise ClipMapError(f"{source}: clip map version must be 1, not {raw.get('version')!r}")

    key = raw.get("key")
    if not isinstance(key, str) or not key:
        raise ClipMapError(f"{source}: clip map has no key")
    if key != source:
        raise ClipMapError(f"{source}: clip map key {key!r} does not match {source!r}")

    label = raw.get("label")
    if not isinstance(label, str) or not label:
        raise ClipMapError(f"{source}: clip map has no label")

    template_key = raw.get("template")
    if not isinstance(template_key, str) or not template_key:
        raise ClipMapError(f"{source}: clip map has no template")
    try:
        template = rigging.get_template(template_key)
    except ValueError as exc:
        raise ClipMapError(f"{source}: {exc}") from exc
    template_bones = {b["name"] for b in template.bones}

    raw_bones = raw.get("bones")
    if not isinstance(raw_bones, Mapping) or not raw_bones:
        raise ClipMapError(f"{source}: clip map has no bones")

    bones: dict[str, tuple[str, ...]] = {}
    claimed: dict[str, str] = {}
    for target, chain in raw_bones.items():
        if target not in template_bones:
            raise ClipMapError(
                f"{source}: maps {target!r}, which the {template_key!r} template does not have"
            )
        if not isinstance(chain, list) or not chain:
            raise ClipMapError(f"{source}: {target!r}'s chain must be a non-empty list")
        names: list[str] = []
        for entry in chain:
            if not isinstance(entry, str) or not entry:
                raise ClipMapError(f"{source}: {target!r}'s chain has an empty bone name")
            if entry in claimed:
                raise ClipMapError(
                    f"{source}: source bone {entry!r} is claimed by both "
                    f"{claimed[entry]!r} and {target!r}"
                )
            claimed[entry] = target
            names.append(entry)
        bones[target] = tuple(names)

    required = raw.get("required")
    if not isinstance(required, list) or not all(isinstance(r, str) and r for r in required):
        raise ClipMapError(f"{source}: required must be a list of bone names")
    missing = [r for r in required if r not in bones]
    if missing:
        raise ClipMapError(f"{source}: required bone(s) {missing} are not mapped")

    root = raw.get("root")
    if not isinstance(root, str) or not root:
        raise ClipMapError(f"{source}: clip map has no root")
    if root not in bones:
        raise ClipMapError(f"{source}: root {root!r} is not mapped")

    strip_pattern = raw.get("strip", "")
    if not isinstance(strip_pattern, str):
        raise ClipMapError(f"{source}: strip must be a string")
    try:
        strip = re.compile(strip_pattern)
    except re.error as exc:
        raise ClipMapError(
            f"{source}: strip pattern {strip_pattern!r} does not compile: {exc}"
        ) from exc

    return ClipMap(
        key=key,
        label=label,
        template=template_key,
        strip=strip,
        required=tuple(required),
        root=root,
        bones=MappingProxyType(bones),
    )


_clip_maps: dict[str, ClipMap] | None = None


def load_clip_maps() -> dict[str, ClipMap]:
    """Every shipped clip map, key -> :class:`ClipMap`. Cached like ``rigging.templates()``.

    **A malformed file costs you that entry, not the loader** -- the same rule
    ``rigging._load_templates`` follows, for the same reason: a hand-edited or
    future third-party clip map dropped beside the shipped two must not be
    able to take Poser's whole "Import clip" feature down with it.
    """
    global _clip_maps
    if _clip_maps is None:
        found: dict[str, ClipMap] = {}
        for path in sorted(CLIP_MAP_DIR.glob("*.json")):
            try:
                raw = rigging._read_json_capped(path, rigging.MAX_TEMPLATE_BYTES)
                clip_map = parse_clip_map(raw, source=path.stem)
                found[clip_map.key] = clip_map
            except Exception:
                log.exception("skipping unusable clip map %s", path)
        _clip_maps = found
    return _clip_maps


def normalise(name: str, clip_map: ClipMap) -> str:
    """Strip ``clip_map``'s external-rig prefix off one bone name.

    A single leading match only (``count=1``): the pattern is authored
    anchored (``^mixamorig\\d*[:_]``) precisely so this never eats more than
    the prefix, and an unanchored accident should not either.
    """
    return clip_map.strip.sub("", name, count=1)


@dataclass(frozen=True, slots=True)
class MatchResult:
    """The outcome of matching a skeleton's bone names against a clip map.

    ``resolved`` is target bone -> the actual (original-spelling) source bone
    names of its chain, only for chains that matched completely. ``left_at_
    rest`` names every target bone whose chain did not -- see :func:`match`'s
    docstring for why a chain is all-or-nothing. ``ignored`` is every source
    bone the winning map's chains never named at all (original spelling,
    sorted) -- fingers, twist bones, end-effectors: real and expected on most
    imports, and reported so the user can see nothing was silently dropped by
    mistake.
    """

    clip_map: ClipMap
    resolved: dict[str, tuple[str, ...]]
    left_at_rest: tuple[str, ...]
    ignored: tuple[str, ...]


def _resolve(
    clip_map: ClipMap, source_bones: list[str]
) -> tuple[dict[str, tuple[str, ...]], list[str], set[str], dict[str, str]]:
    """One candidate's chains against one skeleton -- the shared half of
    scoring a candidate and building the winner's :class:`MatchResult`."""
    by_normal: dict[str, str] = {}
    for name in source_bones:
        by_normal.setdefault(normalise(name, clip_map), name)
    resolved: dict[str, tuple[str, ...]] = {}
    left_at_rest: list[str] = []
    referenced: set[str] = set()
    for target, chain in clip_map.bones.items():
        referenced.update(chain)
        actual_chain = [by_normal.get(src) for src in chain]
        if all(actual is not None for actual in actual_chain):
            resolved[target] = tuple(actual_chain)  # type: ignore[arg-type]
        else:
            left_at_rest.append(target)
    return resolved, left_at_rest, referenced, by_normal


def match(
    source_bones: Iterable[str],
    maps: Mapping[str, ClipMap] | None = None,
    *,
    template: str,
) -> MatchResult:
    """Pick the clip map for ``template`` that best fits ``source_bones``.

    ``maps`` defaults to :func:`load_clip_maps`'s shipped set; a caller (a
    test, or a future user-supplied clip map) may pass its own. Every
    candidate that targets ``template`` and whose ``required`` bones are all
    present (after prefix-stripping) qualifies; among those, the one covering
    the most template bones wins -- e.g. a Rigify metarig with an extra bone
    or two mapped beats one that only satisfies the bare minimum.

    **A chain resolves only if every one of its source bones is present --
    never partially.** Later math (not in this module) reads a resolved
    chain's orientation off its *last* bone and its direction from the first
    bone's head to the last bone's tail; half a two-bone chain has neither a
    trustworthy orientation nor a trustworthy direction, so its target bone is
    left at the template's rest pose instead of being posed off a guess. This
    is also why a bone that belongs to an incomplete chain is not reported in
    ``ignored``: it *was* claimed by a chain, that chain just did not complete.

    Raises :class:`ClipMapError` when no candidate qualifies, naming
    ``template`` and, for whichever candidate came closest, the missing
    required source bone(s) by the map's own spelling (e.g. "missing Hips,
    LeftUpLeg").
    """
    available = load_clip_maps() if maps is None else maps
    candidates = sorted(
        (m for m in available.values() if m.template == template), key=lambda m: m.key
    )
    if not candidates:
        raise ClipMapError(f"no clip map targets the {template!r} template")

    actual = list(source_bones)

    best: tuple[int, ClipMap, dict[str, tuple[str, ...]], list[str], set[str]] | None = None
    closest: tuple[int, ClipMap, list[str]] | None = None
    for clip_map in candidates:
        resolved, left_at_rest, referenced, by_normal = _resolve(clip_map, actual)
        missing_required = [
            src
            for t in clip_map.required
            if t not in resolved
            for src in clip_map.bones[t]
            if src not in by_normal
        ]
        if missing_required:
            if closest is None or len(missing_required) < closest[0]:
                closest = (len(missing_required), clip_map, missing_required)
            continue
        score = len(resolved)
        if best is None or score > best[0]:
            best = (score, clip_map, resolved, left_at_rest, referenced)

    if best is None:
        assert closest is not None  # candidates is non-empty, so one was scored
        _, clip_map, missing_required = closest
        raise ClipMapError(
            f"no clip map for the {template!r} template matches this skeleton "
            f"(closest is {clip_map.label}, missing {', '.join(missing_required)})"
        )

    _, clip_map, resolved, left_at_rest, referenced = best
    ignored = sorted(name for name in actual if normalise(name, clip_map) not in referenced)
    return MatchResult(
        clip_map=clip_map,
        resolved=resolved,
        left_at_rest=tuple(left_at_rest),
        ignored=tuple(ignored),
    )
